export const initialChemicalData = {
  name: '',
  batch: '',
  molecularFormula: '',
  casNumber: '',
  purity: '',
  location: '',
  brand: '',
  supply: '',
  amount: '',
  unit: '',
  dateReceived: '',
  expiryDate: '',
  sds: '',
  hazardClassification: '',
  remarks: '',
};
